AWSTemplateFormatVersion: "2010-09-09"
Resources:
  EnforcerOriginRequestPolicy:
    Type: AWS::CloudFront::OriginRequestPolicy
    Properties:
      OriginRequestPolicyConfig:
        Name: "human-security-enforcer-origin-request-policy"
        QueryStringsConfig:
          QueryStringBehavior: "all"
        CookiesConfig:
          CookieBehavior: "all"
        HeadersConfig:
          HeaderBehavior: allViewer
  FirstPartyOriginRequestPolicy:
    Type: AWS::CloudFront::OriginRequestPolicy
    Properties:
      OriginRequestPolicyConfig:
        Name: "human-security-first-party-origin-request-policy"
        CookiesConfig:
          CookieBehavior: "all"
        HeadersConfig:
          HeaderBehavior: "whitelist"
          Headers:
            - "Origin"
        QueryStringsConfig:
          QueryStringBehavior: "all"
  HumanEnforcerLambda:
    Type: "AWS::Lambda::Function"
    Properties:
      FunctionName: "human-security-enforcer-lambda"
      Handler: "index.handler"
      Role: !GetAtt EnforcerExecutionRole.Arn
      Runtime: "nodejs20.x"
      Code:
        S3Bucket: !Ref HumanLambdaCodeBucket
        S3Key: !Ref EnforcerLambdaCodePath

  HumanEnforcerLambdaFunctionVersion:
    Type: "AWS::Lambda::Version"
    Properties:
      FunctionName: !Ref HumanEnforcerLambda

  EnforcerExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
                - "edgelambda.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "human-security-enforcer-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "*"

  HumanActivitiesLambda:
    Type: "AWS::Lambda::Function"
    Properties:
      FunctionName: "human-security-activities-lambda"
      Handler: "index.handler"
      Role: !GetAtt EnforcerExecutionRole.Arn
      Runtime: "nodejs20.x"
      Code:
        S3Bucket: !Ref HumanLambdaCodeBucket
        S3Key: !Ref ActivitiesLambdaCodePath

  HumanActivitiesLambdaFunctionVersion:
    Type: "AWS::Lambda::Version"
    Properties:
      FunctionName: !Ref HumanActivitiesLambda

  HumanFirstPartyLambda:
    Type: "AWS::Lambda::Function"
    Properties:
      FunctionName: "human-security-first-party-lambda"
      Handler: "index.handler"
      Role: !GetAtt EnforcerExecutionRole.Arn
      Runtime: "nodejs20.x"
      Code:
        S3Bucket: !Ref HumanLambdaCodeBucket
        S3Key: !Ref FirstPartyLambdaCodePath

  HumanFirstPartyLambdaFunctionVersion:
    Type: "AWS::Lambda::Version"
    Properties:
      FunctionName: !Ref HumanFirstPartyLambda

  CloudFrontDistribution:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        Enabled: true
        Origins:
          - DomainName: "<ORIGIN_DOMAIN_URL>"
            Id: "ExampleOrigin"
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: "https-only"
        DefaultCacheBehavior:
            AllowedMethods:
                - "GET"
                - "HEAD"
                - "OPTIONS"
                - "PUT"
                - "POST"
                - "PATCH"
                - "DELETE"
            CachedMethods:
                - "GET"
                - "HEAD"
                - "OPTIONS"
            TargetOriginId: "ExampleOrigin"
            OriginRequestPolicyId: !Ref EnforcerOriginRequestPolicy
            CachePolicyId: "658327ea-f89d-4fab-a63d-7e88639e58f6"  # AWS Managed CachingOptimized Policy
            ViewerProtocolPolicy: "allow-all"
            LambdaFunctionAssociations:
              - EventType: "viewer-request"
                LambdaFunctionARN: !Ref HumanEnforcerLambdaFunctionVersion
              - EventType: "origin-response"
                LambdaFunctionARN: !Ref HumanActivitiesLambdaFunctionVersion
        CacheBehaviors:
          - PathPattern: "<PX_APP_ID_SUFFIX>/*"
            AllowedMethods:
                - "GET"
                - "HEAD"
                - "OPTIONS"
                - "PUT"
                - "POST"
                - "PATCH"
                - "DELETE"
            CachedMethods:
                - "GET"
                - "HEAD"
            TargetOriginId: "ExampleOrigin"
            OriginRequestPolicyId: !Ref FirstPartyOriginRequestPolicy
            CachePolicyId: "658327ea-f89d-4fab-a63d-7e88639e58f6"  # AWS Managed CachingOptimized Policy
            ViewerProtocolPolicy: "allow-all"
            LambdaFunctionAssociations:
              - EventType: "origin-request"
                LambdaFunctionARN: !Ref HumanFirstPartyLambdaFunctionVersion
        ViewerCertificate:
          CloudFrontDefaultCertificate: true

Parameters:
  HumanLambdaCodeBucket:
    Type: String
    Description: "S3 bucket where the Enforcer Lambdas code zip files are stored."

  EnforcerLambdaCodePath:
    Type: String
    Description: "S3 path for the Enforcer Lambda code zip file."

  ActivitiesLambdaCodePath:
    Type: String
    Description: "S3 path for the Activities Lambda code zip file."

  FirstPartyLambdaCodePath:
    Type: String
    Description: "S3 path for the First Party Lambda code zip file."